### ISSUE TITLE
Remplacer ce lien avec un lien vers la documentation

### ISSUE THREAD

**Issue by nriss** [ansforge/IG-service-acces-aux-soins#22]
https://github.com/ansforge/IG-service-acces-aux-soins/blob/5047711ef6c30c1f187d6eac46f61a7f1dda27eb/input/pagecontent/about.md?plain=1#L22

https://github.com/ansforge/IG-documentation

**Comment by cpanissod** [comment]
Ok, will be merged with following branch /feature/improve-fsh-profiles
